name: Deploy Nextjs app to gh-pages

on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      source_branch:
        description: shiki-test repo branch
        required: true
        default: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      NEXT_PUBLIC_BASE_PATH: ''
    strategy:
      matrix:
        node-version: [18.x]
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source_branch }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Checkout gh-pages
        run: |
          mkdir gh-pages
          cd gh-pages
          git init
          git remote add origin https://github.com/sm1990/shiki-test.git
          git fetch origin
          git checkout -b deploy-website-$GITHUB_SHA origin/gh-pages

      - name: Export static files
        run: npm run export

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Rearrange files to match the urls
        run: |
          chmod +x utils/rearrangeFiles.sh
          utils/rearrangeFiles.sh
        shell: bash

      - name: Deploy
        run: |
          cp -r .github CNAME robots.txt gh-pages/.git utils out
          cd out
          git add .
          git commit --allow-empty -m 'Deploy website'
          git push origin deploy-website-$GITHUB_SHA
          echo 'Successfully pushed to deploy-website-$GITHUB_SHA branch'

      - name: Create pull request for new site
        shell: bash
        run: |
          cd out
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          bin/hub pull-request -b gh-pages -m '[Automated] Deploy website'
